# Builds, Creates a release and optionally publishes to NuGet
name: .NET Build, Release & Publish

on:
  workflow_call:
    inputs:
      dotnet_version:
        description: 'Enter version of .NET required, defaults to 8.0.x'
        required: false
        default: '8.0.x'
        type: string
      nuget_endpoint:
        description: 'Proget Publish API Endpoint'
        required: false
        type: string
      nuget_key:
        description: 'API key with permissions to push NuGet packages'
        required: false
        type: string

jobs:
    build-release:
      runs-on: windows-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up .NET
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: ${{ inputs.dotnet_version }}

        - name: Install dependencies
          run: dotnet restore

        - name: Build
          run: dotnet build --configuration Release --no-restore

        - name: Run tests
          run: dotnet test --no-restore --verbosity normal
    
        - name: release-please
          uses: googleapis/release-please-action@v4
          with: 
            release-type: simple

        - name: Pack
          run: dotnet pack --configuration Release --no-build --output ./nupkg

        - name: Publish NuGet
          if: env.NUGET_ENDPOINT != '' && env.NUGET_KEY != ''
          run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ inputs.nuget_key }} --source ${{ inputs.nuget_endpoint }}

env:
  NUGET_ENDPOINT: ${{ inputs.nuget_endpoint }}
  NUGET_KEY: ${{ inputs.nuget_key }}